/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#5f5e5e",
        "primary": "#000000",
        "on-secondary": "#ffffff",
        "inverse-primary": "#c9c6c5",
        "tertiary-container": "#241a0e",
        "error": "#ba1a1a",
        "surface-container": "#eeeeec",
        "on-primary-fixed": "#1c1b1b",
        "on-secondary-fixed-variant": "#23501e",
        "tertiary-fixed": "#f4dfcb",
        "on-primary-container": "#858383",
        "surface-container-lowest": "#ffffff",
        "surface": "#f9f9f7",
        "tertiary": "#000000",
        "on-tertiary-container": "#928170",
        "error-container": "#ffdad6",
        "on-secondary-container": "#3f6d38",
        "primary-fixed-dim": "#c9c6c5",
        "surface-dim": "#dadad8",
        "on-tertiary-fixed": "#241a0e",
        "surface-container-highest": "#e2e3e1",
        "outline-variant": "#c4c7c7",
        "on-surface": "#1a1c1b",
        "secondary": "#3b6934",
        "primary-fixed": "#e5e2e1",
        "secondary-fixed": "#bcf0ae",
        "inverse-on-surface": "#f1f1ef",
        "on-primary": "#ffffff",
        "surface-bright": "#f9f9f7",
        "surface-variant": "#e2e3e1",
        "inverse-surface": "#2f3130",
        "secondary-container": "#b9eeab",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#002201",
        "surface-container-high": "#e8e8e6",
        "tertiary-fixed-dim": "#d7c3b0",
        "on-tertiary-fixed-variant": "#524436",
        "on-error": "#ffffff",
        "outline": "#747878",
        "surface-container-low": "#f4f4f2",
        "secondary-fixed-dim": "#a1d494",
        "on-background": "#1a1c1b",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#474646",
        "primary-container": "#1c1b1b",
        "on-surface-variant": "#444748",
        "background": "#f9f9f7"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xl": "80px",
        "gutter": "24px",
        "md": "24px",
        "base": "8px",
        "sm": "12px",
        "xs": "4px",
        "container-max": "1280px",
        "lg": "48px"
      },
      fontFamily: {
        "headline": ["Libre Caslon Text", "serif"],
        "display": ["Libre Caslon Text", "serif"],
        "body": ["Hanken Grotesk", "sans-serif"],
        "label": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Libre Caslon Text", "serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "headline-sm": ["Libre Caslon Text", "serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Libre Caslon Text", "serif"],
        "display-lg-mobile": ["Libre Caslon Text", "serif"]
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
