/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#1B1D1A",
        "primary": "#1B1D1A",
        "on-secondary": "#ffffff",
        "inverse-primary": "#F4F1EA",
        "tertiary-container": "#D1D8C1",
        "error": "#ba1a1a",
        "surface-container": "#D1D8C1",
        "on-primary-fixed": "#1B1D1A",
        "on-secondary-fixed-variant": "#3b6934",
        "tertiary-fixed": "#D1D8C1",
        "on-primary-container": "#444748",
        "surface-container-lowest": "#ffffff",
        "surface": "#F4F1EA",
        "tertiary": "#1B1D1A",
        "on-tertiary-container": "#1B1D1A",
        "error-container": "#ffdad6",
        "on-secondary-container": "#3b6934",
        "primary-fixed-dim": "#1B1D1A",
        "surface-dim": "#E2E0D8",
        "on-tertiary-fixed": "#1B1D1A",
        "surface-container-highest": "#E2E0D8",
        "outline-variant": "#E2E0D8",
        "on-surface": "#1B1D1A",
        "secondary": "#3b6934",
        "primary-fixed": "#F4F1EA",
        "secondary-fixed": "#D1D8C1",
        "inverse-on-surface": "#F4F1EA",
        "on-primary": "#ffffff",
        "surface-bright": "#F4F1EA",
        "surface-variant": "#E2E0D8",
        "inverse-surface": "#1B1D1A",
        "secondary-container": "#D1D8C1",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#1B1D1A",
        "surface-container-high": "#E2E0D8",
        "tertiary-fixed-dim": "#D1D8C1",
        "on-tertiary-fixed-variant": "#1B1D1A",
        "on-error": "#ffffff",
        "outline": "#747878",
        "surface-container-low": "#D1D8C1",
        "secondary-fixed-dim": "#D1D8C1",
        "on-background": "#1B1D1A",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#1B1D1A",
        "primary-container": "#1B1D1A",
        "on-surface-variant": "#1B1D1A",
        "background": "#F4F1EA"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xl": "80px",
        "gutter": "24px",
        "md": "24px",
        "base": "8px",
        "sm": "12px",
        "xs": "4px",
        "container-max": "1280px",
        "lg": "48px"
      },
      fontFamily: {
        "headline": ["Libre Caslon Text", "serif"],
        "display": ["Libre Caslon Text", "serif"],
        "body": ["Hanken Grotesk", "sans-serif"],
        "label": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Libre Caslon Text", "serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "headline-sm": ["Libre Caslon Text", "serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Libre Caslon Text", "serif"],
        "display-lg-mobile": ["Libre Caslon Text", "serif"]
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
